
spring.datasource.url = jdbc:mysql://centerbeam.proxy.rlwy.net:54604/batdongsan
spring.datasource.username = root
spring.datasource.password =
spring.datasource.password =xAGdMYiWwCluMlzDfjxlmjBfFmKfPxtc

#spring.jpa.hibernate.ddl-auto = none
#spring.jpa.hibernate.ddl-auto = create
@@ -14,4 +14,4 @@ spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
spring.mvc.view.suffix=.jsp
